# Generated by Django 4.2.7 on 2024-04-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
