# Generated by Django 4.2.7 on 2023-11-28 13:20

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_activate',
            field=models.BooleanField(default=bboard.models.is_active_default),
        ),
        migrations.AddField(
            model_name='bb',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
