# Generated by Django 4.2.7 on 2024-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
