# Generated by Django 4.2.7 on 2023-12-05 13:51

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_kind_alter_bb_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100500), django.core.validators.DecimalValidator(8, 2), bboard.models.validate_even, bboard.models.validate_positive], verbose_name='Цена'),
        ),
    ]
