# Generated by Django 5.0.1 on 2024-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_bb_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, default='Какое-то значение: ', null=True, verbose_name='Описание'),
        ),
    ]
