# Generated by Django 5.0.3 on 2024-03-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_bb_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
