# Generated by Django 5.0.1 on 2024-02-27 15:22

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
from django.db import migrations, models

from django.contrib.postgres.operations import (CreateExtension,
                                                BtreeGistExtension,
                                                CITextExtension)


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        CreateExtension(name='hstore'),
        BtreeGistExtension(),
        CITextExtension(),
        migrations.CreateModel(
            name='PGSProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), size=None, verbose_name='Использованные платформы')),
            ],
        ),
        migrations.CreateModel(
            name='PGSRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None, verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='PSGProject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('platforms', django.contrib.postgres.fields.hstore.HStoreField(verbose_name='Использованные платформы')),
            ],
        ),
        migrations.CreateModel(
            name='PSGProject3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=40, verbose_name='Название')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PGSRoomReserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Помещение')),
                ('reserving', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Время резервирования')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменить резервирование')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['reserving'], fillfactor=50, name='i_pgsrr_reserving', opclasses=('range_ops',))],
            },
        ),
        migrations.AddConstraint(
            model_name='pgsroomreserving',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('cancelled', False)), expressions=[('name', '='), ('reserving', '&&')], name='c_pgsrr_reserving'),
        ),
        migrations.AddIndex(
            model_name='pgsrubric',
            index=models.Index(fields=['name', 'description'], name='i_pgsrubric_name_description', opclasses=('varchar_pattern_ops', 'bpchar_pattern_ops')),
        ),
        migrations.AddConstraint(
            model_name='pgsrubric',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('name', '='), ('description', '=')], name='c_pgsrubric_name_description'),
        ),
    ]
