# Generated by Django 5.0.1 on 2024-02-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_message_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinePrice',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.machine')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('testapp.machine',),
        ),
        migrations.CreateModel(
            name='MachineMaintenance',
            fields=[
                ('machineprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.machineprice')),
                ('maintenance_schedule', models.TextField()),
            ],
            bases=('testapp.machineprice',),
        ),
    ]
