# Generated by Django 4.2.7 on 2024-03-28 16:23

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCodeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_bbcode_content_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('bbcode_content', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
