# Generated by Django 5.0.1 on 2024-03-01 15:31

import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_img_alter_pgsroomreserving_reserving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to=testapp.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
